node {
        stage('Checkout') {
            git url: 'https://github.com/bahti/dcos-sample.git', branch: 'master'
        }

        stage('Build') {
            def mvnTool = tool 'maven'
            bat "${mvnTool}/bin/mvn clean install -f ./config/pom.xml"
            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('account-service') {
                def app = docker.build "bahtiyarkaba/config:${env.version}"
                app.push()
            }
        }

        stage ('Deploy') {
            def body = readFile file: 'config/marathon.json'
            httpRequest contentType: 'APPLICATION_JSON', httMode: 'PUT', url: 'http://192.168.216.80/v2/apps/', requestBody: body
        }     
}